### ISSUE TITLE
The `gitlab-auth.sh` is broken 

### ISSUE THREAD

**Issue by logist322** [instrumentisto/toolchain#12]
The `gitlab-auth.sh` is broken. Presumably, it is broken somewhere into [the second step in the genGitlabToken()](https://github.com/instrumentisto/toolchain/blob/b0820b7ec4c9e7b015ed707913f61769137733c2/kubernetes/gitlab-auth.sh#L75).

**Comment by tyranron** [comment]
@logist322 issue the PR with the fix. Thanks!
